CONFIG_ZMK_INPUT_AMS_AS5600=y
# Stromsparmodus mit 20ms-Abtastintervall (LPM2 = 20ms default-Polling im Sensor selbst)
CONFIG_ZMK_INPUT_AMS_AS5600_POWER_MODE_LPM3=y

# Interner Filter des Sensors:
CONFIG_ZMK_INPUT_AMS_AS5600_HYSTERESIS_2LSB=y          # Kleine Schwelle gegen Rauschen
CONFIG_ZMK_INPUT_AMS_AS5600_SLOW_FILTER_8X=y           # Guter Glättungseffekt
CONFIG_ZMK_INPUT_AMS_AS5600_FAST_FILTER_THRESHOLD_10LSB=y # Reagiert auf größere Bewegungen

# Watchdog im Sensor aktivieren
CONFIG_ZMK_INPUT_AMS_AS5600_WATCHDOG_TIMER=y

CONFIG_ZMK_INPUT_AMS_AS5600_POLL_INTERVAL=20
CONFIG_SENSOR=y


CONFIG_ZMK_EXT_POWER=n
# CONFIG_ZMK_INPUT=y
CONFIG_ZMK_INPUT_AMS_AS5600=y
# CONFIG_LOG=y
# CONFIG_LOG_DEFAULT_LEVEL=3
# # CONFIG_ZMK_INPUT_AMS_AS5600_LOG_LEVEL=4
# CONFIG_ZMK_INPUT_AMS_AS5600_LOG_AGC=y