CONFIG_ZMK_KEYBOARD_NAME="corax56"

# Sensor-Unterstützung (z. B. AS5600)
CONFIG_SENSOR=y
CONFIG_INPUT_LOG_LEVEL_DBG=y

# Optional: zusätzliche Debug-Ausgabe (nicht Pflicht)
CONFIG_LOG=y

# Optional: Verhalten verbessern
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_IDLE_TIMEOUT=30000

# Display deaktivieren, falls nicht benutzt
CONFIG_ZMK_DISPLAY=n

CONFIG_ZMK_INPUT_AMS_AS5600=y
CONFIG_ZMK_INPUT_AMS_AS5600_LOG_AGC=y


# CONFIG_ZMK_INPUT_AMS_AS5600_POWER_MODE_LPM2=y # LPM2: Polling time = 20ms
# CONFIG_ZMK_INPUT_AMS_AS5600_HYSTERESIS_2LSB=y # 2 LSB
# CONFIG_ZMK_INPUT_AMS_AS5600_SLOW_FILTER_8X=y
# CONFIG_ZMK_INPUT_AMS_AS5600_FAST_FILTER_THRESHOLD_7LSB=y # 7 LSBs
# CONFIG_ZMK_INPUT_AMS_AS5600_WATCHDOG_TIMER=y

# Power mode
CONFIG_ZMK_INPUT_AMS_AS5600_POWER_MODE_NOM=y

# Hysteresis
CONFIG_ZMK_INPUT_AMS_AS5600_HYSTERESIS_OFF=y

# Slow filter
CONFIG_ZMK_INPUT_AMS_AS5600_SLOW_FILTER_16X=y

# Fast filter
CONFIG_ZMK_INPUT_AMS_AS5600_FAST_FILTER_THRESHOLD_SLOW_ONLY=y

# Watchdog (optional)
CONFIG_ZMK_INPUT_AMS_AS5600_WATCHDOG_TIMER=y
