manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: urob
      url-base: https://github.com/urob

    - name: local
      url-base: ""




  projects:
    - name: zmk
      import: app/west.yml
      remote: zmkfirmware
      revision: main
    - name: zmk-driver-ams-as5600
      path: modules/sensor/zmk-driver-ams-as5600
      remote: local
      url: ""
      revision: main

    # - name: zmk-studio-messages
    #   path: modules/msgs/zmk-studio-messages
    #   url: https://github.com/zmkfirmware/zmk-studio-messages
    #   revision: main

  self:
    path: config
