on:
  push:
    branches: [ "main", "main2", "rotary2","rotary3","rotary3-2", "build"  ]
  pull_request_target:
    branches: [ "main" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
